Propagate outputs from create-pr step

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -24,11 +24,20 @@ jobs:
       with:
         persist-credentials: false
                        
-    - name: Test 
+    - name: Test
+      id: update
       uses: bennettoxford/update-dependencies-action@v1
       with: 
         update_command: "echo updated > update.txt"
         on_changes_command: "echo changed > on_changes.txt"
         pr_title: "PR from test run on ${{ github.ref_name }}"
         automerge: false
-  
+
+    - name: Check PR created output
+      run: |
+          set +e
+          if [ "${{ steps.update.outputs.pull-request-operation }}" != "created" ]; then
+            echo "::error::Expected PR operation created, found ${{ steps.update.outputs.pull-request-operation }}"
+            exit 1
+          fi
+      shell: bash
